### ISSUE TITLE
dodanie kodu erpy_daj

### ISSUE THREAD

**Issue by idakozarow** [mmagnuski/AnalizaDanychEEG01#10]
Pomooocy! Nie mogę sobie poradzić w żaden sposób z dodaniem do ścieżki matlaba kodu "erpy_daj". Ktoś pomoże?

**Comment by mmista** [comment]
Powiedz co robisz ?
Czy udaje Ci się ustawić "seth path" (w celu załadowania danych eeglab'a) ?
jeżeli tak to jest to ta sama procedura. Najszybciej to do tego folderu w
którym znajduje się twój eeglab wrzuć plik erpy_daj.

Np. ja w C/user/documents/eeglab 13.4.4  mam eeglaba i  kiedy klikam "set
path" i klikam add folder to ustawiam tą ścieżkę. do folderu eeglab 13.4.4
wrzuciłem erpy_daj któe pojawiły się następnie w okienku matlaba po lewej
stronie.

2015-06-21 0:21 GMT+02:00 idakozarow notifications@github.com:

**Comment by idakozarow** [comment]
Hmm...spróbowałam użyć tego sposobu, wrzuciłam erpy-daj do folderu z eeglabem, niestety cały czas dostaję odpowiedz :
Error using erpy_daj (line 11)
Not enough input arguments.

**Comment by idakozarow** [comment]
już, mam wszystko, dziękuję bardzo, dodałam funkcję, ale w pewnym momencie nie używałam jej tak jak trzeba

**Comment by mmagnuski** [comment]
cieszy mnie że pomagacie sobie :smiley:

**Comment by idakozarow** [comment]
o! dobrze, że jesteś, mam kolejny problem ;P nie mogę zmusić wykresów, żeby nadpisywały się na siebie, czytaj: mam problem z funkcją hold on

**Comment by mmagnuski** [comment]
Sprawdź czy coś takiego działa:

``` matlab
figure; hold on;
plot(rand(10, 1), 'r');
plot(rand(10, 1), 'g');
```
