### ISSUE TITLE
błąd fuckcji?

### ISSUE THREAD

**Issue by EdSkamor** [mmagnuski/AnalizaDanychEEG01#11]
wrzucam coś takiego:
plot(EEG.times, erp_0, 'g');
plot(EEG.times, erp_180, 'r');
a matlab udzlela mi niemiłej czerwonej odpowiedzi: Undefined function or variable 'erp_0'.
Co ja mam niezdefiniowane i co zrobić by działało?
Próbuję wytworzyć dwa wykresy które będę mógł swobodnie pokolorować.

**Comment by bbednarz** [comment]
Jest już 2 dni po terminie oddania pracy więc teraz już Nic nie musisz.

W dniu piątek, 3 lipca 2015 EdSkamor notifications@github.com napisał(a):

**Comment by bbednarz** [comment]
TA wcześniejsza wiadomość była docelowo do Kuby więc przepraszam za
przypadkowe zamieszanie poczty.

W dniu sobota, 4 lipca 2015 Bartosz Bednarz bbednarz@st.swps.edu.pl
napisał(a):

**Comment by mmagnuski** [comment]
`Undefined function or variable 'erp_0'.` znaczy tyle, że mienna `erp_0` u Ciebie nie istnieje. Zobacz co zrobiłeś wcześniej tzn jak nazwałeś erpy, może po prostu `erp` a nie `erp_0`?
