### ISSUE TITLE
Odrabianie zajęć

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/AnalizaDanychEEG01#12]
## odrabiamy zajęcia

W tygodniu **6 - 10 czerwca 2016** musimy odrobić odwołane zajęcia.
Dotyczy to studentów z grupy `piątek 12:00` jak i grupy `piątek 13:30`.
Nie musimy jednak ustalać oddzielnych zajęć dla jednej i drugiej grupy - ustalimy dwa terminy, które będą umożliwiać jak największej liczbie osób na udział w zajęciach oraz nie doprowadzą do tego, że nie pomieścimy się w sali.
### terminy

Poniżej macie screenshota dostępności sali S220 w następnym tygdoniu (6-10 czerwca).
Proszę dajcie mi znać jakie terminy są sensowne (tzn. nie kolidują z innymi Waszymi zajęciami szkolnymi itp). 
![image](https://cloud.githubusercontent.com/assets/8452354/15724185/41be0c3e-2846-11e6-95af-aaf20a71fa82.png)
### jak "głosować"

:exclamation: Jako że będę zczytywał Wasze odpowiedzi automatycznie bardzo ważne jest abyście odpowiadali w tym wątku w bardzo określony sposób. 
Każdy termin, który chociażby jako tako Wam pasuje wypiszcie podając jego adres z excelowej tabelki w screenshocie. Adres podajemy jako dwa znaki: literę, oznaczającą kolumnę oraz numer oznaczający wiersz. Na przykład _wtorek 13:45-15:15_ to `C5` a _piątek 08:30-10:00_ to `F2`. Podajcie **wszystkie** pasujące Wam terminy rozdzielając je spacjami, np.:

```
B3 B4 B5 C5 C6 D2
```

Bardzo ważne jest aby każda osoba zagłosowała - w związku z tym każdy kto nie zagłosuje będzie miał nieobecność! Głosowanie trwa do soboty, godziny 17:00. Oczywiście nie ma sensu głosować na terminy, w których sala jest zajęta.

**Comment by juustte** [comment]
E4 E6 E7 F6 F7

**Comment by jakubmatyszewski** [comment]
B5 D6 F6 F7

**Comment by gacek91** [comment]
D2 E4 E6

**Comment by FNCY** [comment]
B5 B6 D6

**Comment by violettaz** [comment]
B5 C6 F6

**Comment by tomsitoms** [comment]
B5 C6 F6

**Comment by mmista** [comment]
B5 C6 E6

**Comment by inezgiemza** [comment]
B5 B6 E4

**Comment by oborkowska** [comment]
B7 B8 C2 C4 C5 C6 D6 D7 D8 E4 E6 E7 E8 F6

**Comment by moniakow** [comment]
B5 B6 B7 B8 
C4
D6 D7 D8 
E4

**Comment by Linace123** [comment]
C5 C6 C7 D5 D6 D7 E4 E6 E7

**Comment by majmis** [comment]
B5 C4 C5 D6 E4

**Comment by mraciborski** [comment]
B5 C4 D6

**Comment by kasiado** [comment]
b5, b6, c5, d6, e4

**Comment by Mariszka** [comment]
C2, C3, C7, C8
D6, D7, D8
F6, F7, F8

**Comment by kpijor** [comment]
B7 C3 C5 D7 E4 E6 F6 F7

**Comment by jzamojska** [comment]
B5 B6 B7 C7 D6 D7 F6

**Comment by kuchart** [comment]
B5 B6  C7 D5 E2 E4

**Comment by wiktoriakowalczyk** [comment]
B5 B6 E4

**Comment by n-ruban** [comment]
C5 C6 B6

**Comment by hubertwoz** [comment]
B5 C4 C5 D6 D7 D8 E4 E6 E7 E8  F6 F7 F8

**Comment by mmagnuski** [comment]
Hej, dzięki za głosowanie!
Niestety ze względu na to, że dopiero dzisiaj zdążyłem do tego przysiąść - odpada nam poniedziałek, który miał w sobie jeden z najlepszych terminów.
Wynik przeliczenia głosów:

```
Zagłosowało 21 osób
Pary terminów, które maksymalizują liczbę obecnych osób (16):
wt 15:30-17:00 oraz czw 12:00-13:30
śr 15:30-17:00 oraz czw 12:00-13:30
czw 12:00-13:30 oraz pt 15:30-17:00
```

Jako że mamy 3 pary terminów, które dają nam maksymalną możliwą sumaryczną liczbę obecnych unikatowych osób, pozwoliłem sobie wybrać te, które pasują mi najbardziej, a mianowicie:

> `śr 15:30-17:00 oraz czw 12:00-13:30`

Bardzo proszę abyście byli na jednym z tych terminów - będę normalnie sprawdzał listę obecności.

Na najbliższych zajęciach (tych odrabianych):
-  zobaczymy jak automatycznie zaznaczać oraz wyrzucać złe epoki
- nauczymy się robić potencjały wywołane
- dostaniecie kilka zestawów danych aby poćwiczycie sobie czyszczenie (tyle ile zdążycie na zajęciach - resztę w domu)

Na kolejnych (normalnych piątkowych):
- wrócimy do potencjałów wywołanych i nauczymy się widma ( :skull: uwaga, będzie trochę kodu :skull: )
- wrócimy też do tworzenia sobie skryptu do automatycznego przetwarznia danych (poza klasyfikacją komponentów) ( :skull: uwaga, będzie trochę kodu :skull: )
- jeżeli starczy czasu - pokażę Wam jeszcze analizę czas-częstość (na elektrodach oraz komponentach)

**Comment by hubertwoz** [comment]
zajęcia odrabiane odbywają się w tej samej sali w której piątkowe tak?

**Comment by mmagnuski** [comment]
@hubertwoz Tak jest - odrabiane zajęcia odbywają się w `S220`. 
Nie przejmujcie się też jak Wam się na wirtualnej uczelni wyświetli tylko jeden termin. Formalnie dział planowania SWPS musi to tak wpisać w planie - jedna grupa - jedno spotkanie.

BTW - jeżeli Was interesuje jak liczyłem głosy - wrzuciłem do folderu `kod` notebook `liczenie głosów.ipynb` - możecie sobie zajrzeć, na githubie wszystko się renderuje, nie trzeba ściągać.
To nie jest nic obowiązkowego, także nie przejmujcie się jeżeli wygląda strasznie.
