### ISSUE TITLE
Projekty

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/AnalizaDanychEEG01#13]
Tutaj wpisujcie kto bierze jaki dataset.

**Comment by gacek91** [comment]
Ja biorę CAT206 20131103 1727002

**Comment by Linace123** [comment]
ja biorę CAT201, przynajmniej wstępnie rezerwuję

**Comment by Schuhunova** [comment]
Biorę CAT306 20131110 1241002

**Comment by jakubmatyszewski** [comment]
CAT203 20130723 1330002

**Comment by tomsitoms** [comment]
CAT104 task2

**Comment by EkaterinaIsakova** [comment]
CAT102 task2

**Comment by EkaterinaIsakova** [comment]
CAT311 20131209 1929002

**Comment by majmis** [comment]
CAT207 20131103 1845002

**Comment by moniakow** [comment]
CAT303

**Comment by juustte** [comment]
CAT301 task2

**Comment by kpijor** [comment]
CAT310

**Comment by gacek91** [comment]
170

**Comment by AnnaMayDi** [comment]
CAT 101

**Comment by jzamojska** [comment]
CAT 208

**Comment by kasiado** [comment]
CAT309

**Comment by AnastazjaR** [comment]
CAT170 20131027 1756002

**Comment by n-ruban** [comment]
CAT209 20131105 1241002

**Comment by oborkowska** [comment]
Do kiedy musimy wysłać raport???

**Comment by mmagnuski** [comment]
Najlepiej do środy - inaczej mogę nie zdążyć sprawdzić wszystkiego.

**Comment by wiktoriakowalczyk** [comment]
CAT307 20131110 1631002

**Comment by inezgiemza** [comment]
CAT308 20131113 2131002.fdt

**Comment by hubertwoz** [comment]
CAT 109

**Comment by kuchart** [comment]
CAT 302

**Comment by hubertwoz** [comment]
ZMIENIAM NA CAT 304!!!!!!!!

**Comment by Mariszka** [comment]
CAT312 20131209 2056002

ZMIENIAM na CAT205 20131103 1555002

**Comment by FNCY** [comment]
CAT206 20131103

**Comment by wrzos** [comment]
cat111

zmieniam na cat212 (ten niższy)

**Comment by violettaz** [comment]
CAT 305

**Comment by oborkowska** [comment]
CAT210 20131110 1422002

**Comment by mmagnuski** [comment]
Śpieszcie się - projektów złożonych w poniedziałek prawdopodobnie już nie zdążę sprawdzić.

**Comment by EmiliaSz** [comment]
CAT 312
