### ISSUE TITLE
Cóż to jest?

### ISSUE THREAD

**Issue by gacek91** [mmagnuski/AnalizaDanychEEG01#14]
![image](https://cloud.githubusercontent.com/assets/19230487/16522726/cfcee046-3f9f-11e6-98d1-934c211d211c.png)

Czymże są te dziwne "zgrubienia" w okolicach ostatnich elektrod?

**Comment by mmagnuski** [comment]
Chodzi o sygnał w wyższej częstotliwości tzn. lekkie artefakty mięśniowe? Czy to że sygnał bardziej "lata" (wolne zmiany tzn niskie częstotliwości)?

**Comment by gacek91** [comment]
Zaznaczyłem o co mi chodziło :)
![cfcee046-3f9f-11e6-98d1-934c211d211c](https://cloud.githubusercontent.com/assets/19230487/16660852/80db5426-4470-11e6-9ad1-f052ce81d2e3.png)

**Comment by mmagnuski** [comment]
To artefakty mięśniowe (zauważ zresztą, że występują na wielu więcej elektrodach, ale słabiej). Jeżeli w pliku jest tego typu artefaktów sporo - ICA powinno sobie z nimi poradzić.
