### ISSUE TITLE
EEGLAB error (206)

### ISSUE THREAD

**Issue by jakubmatyszewski** [mmagnuski/AnalizaDanychEEG01#15]
Hej, przy filtrowaniu danych w EEGLabie dostaję błąd 206. Błąd występuje na każdym pliku - próbowałem chociażby 'CAT302 task2.set' - czyli ten, na którym ćwiczyliśmy na zajęciach. 
Googlowałem info na ten temat, ale z mizernymi skutkami. Reinstalowałem też MatLab'a (różne wersje 2016a i 2012b), a nawet próbowałem z różnymi wersjami eeglab'a (nowe/archwialne). Nic nie pomogło.

Tutaj screeny z błędem: http://imgur.com/a/tVbkZ
Cóż poradzić?

**Comment by mmagnuski** [comment]
Hm, kojarzę ten błąd, ale nie pamiętam skąd przybył. Proponuję w takiej kolejności:
- zajrzałem w kod `pop_eegfiltnew` - wygląda na to, że funkcja `freqz` jest częścią signal processing toolbox, którego możesz nie mieć. Możesz to sprawdźić tak:
  
  ``` matlab
  v = ver();
  czy_mam_sigproc = any(strcmp('Signal Processing Toolbox', {v.Name}))
  ```
  
  Możesz to też sprawdzić pisząc po prostu:
  
  ``` matlab
  ver
  ```
  
  i sprawdzając czy `Signal Processing Toolbox` jest pośród wymienionych toolboxów.
  Stawiam na to, że go nie masz.
- Dobra wiadomość jest taka, że ta funkcja wyswietla odpowiedź częstotliwościową filtra, a więc nie powinieneś mieć tego błędu gdy odznaczysz checkbox `plot frequency response` czy jakoś tak.

**Comment by mmagnuski** [comment]
Odniesienie do kolejności nieistotne, zacząłem pisać zanim dokładnie sprawdziłem skąd może być błąd.

**Comment by jakubmatyszewski** [comment]
Zgadza się, nie mam Signal Processing Toolbox'a. No cóż, odznaczyłem 'plot frequency response' i działa, więc chyba przeżyję. Dzięki!
