### ISSUE TITLE
Identyfikacja elektrod w widmie

### ISSUE THREAD

**Issue by Linace123** [mmagnuski/AnalizaDanychEEG01#16]
Właściwie już skończyłam projekt. Chciałam jeszcze porównać widmo na wybranych elektrodach. Wyodrębniłam widmo dla dwóch elektrod. I niestety komenda podana w tutorialu nie zwraca mi nazwy elektrody. Kiedy na wykresie są dwie elektrody, nazywa je 1 i 2, a komenda 
EEG.chanlocs(1).labels dodaje tylko literkę C. W końcu ja wiem, jakie elektrody wyodrębniałam, tylko chciałam wiedzieć która to która na wykresie mocy
Liczę, że jest jakiś sposób
Celina Grundland

**Comment by mmagnuski** [comment]
Jak plotujesz widmo? Można odpowiednio ustawić kolory linii i legendę, ale to zależy od tego jak plotujesz (gui czy komendą? a jeżeli komendą to jaką).
jeżeli plotujesz widmo dla elektrody numer 5 i 8 to ich nazwy to odpowiednio:

```
EEG.chanlocs(5).labels
EEG.chanlocs(8).labels
```

Na wszelki wypadek możesz mi wkleić co Ci się pojawia jak wykonasz:

```
ch_names = {EEG.chanlocs.labels}
```

Jedna litera to podejrzana sprawa, może napisałaś `EEG.chanlocs(1).labels(1)`? Wtedy dostaniesz pierwszą literę nazwy elektrody.

**Comment by Linace123** [comment]
Zastosowałam skrypt
figure;   pop_spectopo(EEG, 1, [-252  496], 'EEG' , ...
    'freq', [6 10 22], 'freqrange',[1 50],'plotchans', [30, 44], 'electrodes','off');
Potem z wykresu uzyskałam numer kanału i wpisałam EEG.chanlocs(2). labels
 
wklejam, co mi wyszło po zastosowaniu komend

**Comment by mmagnuski** [comment]
Jeżeli stosujesz skrypt:

``` matlab
figure; pop_spectopo(EEG, 1, [-252, 496], 'EEG' , ...
    'freq', [6, 10, 22], 'freqrange', [1, 50], ...
    'plotchans', [30, 44], 'electrodes', 'off');
```

to plotujesz elektrody 30 i 44 (`plotchans` wynosi `[30, 44]`), a więc aby sprawdzić ich etykiety piszesz `EEG.chanlocs(30).labels` oraz `EEG.chanlocs(44).labels`. `pop_spectopo` najwyraźniej po kliknięciu mówi Ci tylko, który z kolei spośród wybranych do plotowania kanałów kliknęłaś.

Możesz w związku z tym robić tak, gdy chcesz sprawdzić nazwy kanałów:

``` matlab
chans_to_plot = [30, 44] % zależy jakie kanały Cię interesują
figure; pop_spectopo(EEG, 1, [-252, 496], 'EEG' , ...
    'freq', [6, 10, 22], 'freqrange', [1, 50], ...
    'plotchans', chans_to_plot, 'electrodes', 'off');
```

Teraz po kliknięciu na linię widma, gdy wyświetlana jest wartość `1` oznacza to, że elektroda to:

``` matlab
elektroda = chans_to_plot(1);
% a etykieta:
EEG.chanlocs(elektroda).labels
```

**Comment by moniakow** [comment]
![zrzut ekranu 2016-07-09 o 19 18 42](https://cloud.githubusercontent.com/assets/18737946/16710794/05696620-460a-11e6-987f-c729756d11dd.png)
to chyba nie jest najładniejsze widmo? Czy to znaczy że źle przefiltrowałam dane??

**Comment by mmagnuski** [comment]
Jest ok. Nie musi być najładniejsze :)
