### ISSUE TITLE
Jak wrzucamy projekty

### ISSUE THREAD

**Issue by tomsitoms** [mmagnuski/AnalizaDanychEEG01#17]
Wysyłamy na maila pliki ze screenami, opisem i kodem? :)

**Comment by mmagnuski** [comment]
Tak, jeden plik z tekstem i screenami, drugi z wyczyszczonym kodem.

Wystarczy jak wyrzucicie z kodu:
- `eeg_checkset`
- `pop_eegplot`

**Comment by mmagnuski** [comment]
I upewnijcie się że jak zrestartujecie matlaba i puścicie kod to odtwarzają się wyniki.
