### ISSUE TITLE
Przesłany projekt

### ISSUE THREAD

**Issue by Linace123** [mmagnuski/AnalizaDanychEEG01#18]
Mogę prosić o potwierdzenie, że projekt dotarł :)
Celina Grundland

**Comment by mmagnuski** [comment]
Nie znajduję na poczcie swej. Z jakiego maila został wysłany i czy jako oddzielny mail (w wątkach pośród wielu maili łatwo się projekty gubią)?

**Comment by Linace123** [comment]
Super, że właśnie w spamie znalazłam info, że nie dotarł. Wysyłam jeszcze raz
 
W dniu 2016-07-11 00:52:33 użytkownik Mikolaj Magnuski notifications@github.com napisał:
Nie znajduję na poczcie swej. Z jakiego maila został wysłany i czy jako oddzielny mail (w wątkach pośród wielu maili łatwo się projekty gubią)?

**Comment by mmagnuski** [comment]
Nie ma załączników.
12 lip 2016 00:11 "Linace123" notifications@github.com napisał(a):

> Super, że właśnie w spamie znalazłam info, że nie dotarł. Wysyłam jeszcze
> raz
> 
> W dniu 2016-07-11 00:52:33 użytkownik Mikolaj Magnuski <
> notifications@github.com> napisał:
> Nie znajduję na poczcie swej. Z jakiego maila został wysłany i czy jako
> oddzielny mail (w wątkach pośród wielu maili łatwo się projekty gubią)?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/mmagnuski/AnalizaDanychEEG01/issues/18#issuecomment-231881432,
> or mute the thread
> https://github.com/notifications/unsubscribe/AID5Ami3xpZGi9UAk7U2OJZcH-p5jAJDks5qUr-MgaJpZM4JI69O
> .

## 

---

**Comment by Linace123** [comment]
Wysłałam jeszcze raz

Pozdrawiam z mojego telefonu
Celina Grundland 

Dnia 12.07.2016 o godz. 08:49 Mikolaj Magnuski notifications@github.com napisał(a):

**Comment by AnnaMayDi** [comment]
Mogę  również prosić o potwierdzenie, że projekt dotarł? 
Anna Dontsova

**Comment by mmagnuski** [comment]
Potwierdzam.
Zaraz Wam wrzucę tabelkę od kogo dostałem.
Sprawdzam w kolejności chronologicznej - więc osoby które wcześniej oddały mają szanse zastosować się do ewentualnego feedbacku.

**Comment by mmagnuski** [comment]
Może jednak nie wrzucę tabelki - dużo dostałem projektów. Wolę je sprawdzać niż robić tablekę. :stuck_out_tongue:
