### ISSUE TITLE
Nie mogę zrobić ERPów

### ISSUE THREAD

**Issue by gacek91** [mmagnuski/AnalizaDanychEEG01#19]
![zrzut ekranu 2016-07-14 o 11 06 45](https://cloud.githubusercontent.com/assets/19230487/16834273/61ce13be-49b3-11e6-9f2e-8be5943d1933.png)

Robię wszystko tak jak na naszych spotkaniach, zmieniałem nawet bazy danych (5 razy) - za każdym razem wyskakuje mi taki błąd. Jakieś pomysły?

**Comment by mmagnuski** [comment]
Wygląda na to jakby dwa datasety, które chcesz porównać miały inne epokowanie, albo coś w tym stylu. Trudno mi pomóc bez dokładniejszych informacji.
