### ISSUE TITLE
Kiedy odrabiamy stracony czas?

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/AnalizaDanychEEG01#4]
Hejże,
przypominam studentom z grupy piątkowej, że obiecałem odrobić zajęcia, o które jesteśmy w plecy.
Najbliższe zajęcia grupy piatkowej są 12 czerwca, w związku z tym należałoby spotkać się przed tym terminem jeszcze.
#### Moje propozycje:

1) PONIEDZIAŁEK (1 czerwca):
a) 12:00 - 13:30
b) 13:45 - 15:15

2) WTOREK (2 czerwca)
a) 10:15 - 11:45
b) 13:45 - 15:15
c) 15:30 - 17:00

3) PONIEDZIAŁEK (8 czerwca)
a) 12:00 - 13:30
b) 13:45 - 15:15

4) WTOREK (9 czerwca)
a) 10:15 - 11:45
b) 13:45 - 15:15
c) 15:30 - 17:00

5) ŚRODA (10 czerwca)
a) 10:15 - 11:45
c) 15:30 - 17:00
#### Jak głosować?

Każdy z terminów oceńcie na skali 0-5, gdzie:  
`0` - totalna klapa, inne kolidujące zajęcia, nie da się, nie da się, nie da się
`5` - absolutnie fantastyczny termin, chcę, chcę, chcę!  

Wasze głosy będę zczytywał automatycznie, więc ważne jest abyście stosowali się do zasad.  
1. Podstawowy format to `termin - ocena` przy czym termin opisujemy zestawieniem numeru i litery. Poniedziałek (8 czerwca) 12:00 to wg. powyższej rozpiski 3a. A więc jeżeli termin ten chcecie ocenić na 4 piszecie: `3a - 4`
2. Można grupować oceny -  jeżeli wszystkie terminy jednego dnia oceniamy tak samo możemy zgrupować je po lewej stronie, a po myślniku po prawej stronie wpisać jedną ocenę. Np. jeżeli cały wtorek 2 czerwca jest do bani możecie napisć: `2abc - 0` albo po prostu `2 - 0`
3. Przy grupowaniu ocen z różnych dni, rozdzielajcie dni średnikiem. Np. `1a;2;3b - 2`
4. Termin, któremu nie przypiszecie oceny jest traktowany tak jakby wam kompletnie nie pasował (`0`)

Przykład:

```
1a - 3
1b - 1
2abc - 0
3;4abc - 4
5a - 5
5b - 2
```

**Comment by WandaZ** [comment]
1a,b - 0
2a,b - 0
2c - 4
3a,b - 0
4a - 3
4b,c - 5
5a,b - 5

pozdrawiam
Wanda Zarzycka

W dniu 29 maja 2015 18:38 użytkownik Mikolaj Magnuski <
notifications@github.com> napisał:

**Comment by ZbyszekZ** [comment]
1a,b - 0
2a,b - 0
2c - 4
3a,b - 0
4a - 3
4b,c - 5
5a,b - 5
pozdrawiam
Zbigniew Zarzycki

W dniu 31 maja 2015 20:09 użytkownik WandaZ notifications@github.com
napisał:

**Comment by msliwinska** [comment]
1 a,b -0
2 a,b -0
3 a -5
3b -0
4 a, c -0
4b -5
5a -0
5c -4

Monika Śliwińska
31 maj 2015 20:11 "ZbyszekZ" notifications@github.com napisał(a):

**Comment by bpietka** [comment]
3a,b - 5
4 a,b - 5
4 c - 2
5 a -5
5 b - 2

**Comment by wiisienka48** [comment]
3a - 4
3b - 0
4a - 0
4b - 5
4c - 0
5a - 1
5c - 3

**Comment by marek123271** [comment]
3a-0
3b-0
4a-0
4b-0
4c-5
5a-3
5c-5

**Comment by Bruno1208** [comment]
1a,b - 0
2a,b - 0
2c - 0
3a - 0
3b-5
4a - 0
4b,c - 0
5a,b - 5

2015-06-06 10:35 GMT+02:00 marek123271 notifications@github.com:

**Comment by Juliajools** [comment]
3  a,b - 0
4 a - 0
4 b - 5
4 c - 0
5 a,b - 2
