### ISSUE TITLE
Rozdzielamy dane i porównania

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/AnalizaDanychEEG01#5]
W ramach projektu każdy z Was będzie musiał zrobić porównanie erpów oraz widm (więcej info w wiki [tutaj](https://github.com/mmagnuski/AnalizaDanychEEG01/wiki/projekt)).
Każdy z Was może sobie wybrać plik z danymi oraz porównanie jakie chce zrobić. Możliwe porównania to takie, które są zgodne z kanonem jedynej różnicy tzn. porównujemy warunki tak, że różni je tylko kąt obrotu albo rodzaj bodźca. Porównywanie warunków różniących się jednym i drugim w takiej analizie nie ma sensu - bo nie wiemy wtedy z czego wynikają zaobserwowane różnice w sygnale (tzn w ERP).

Dane są [tutaj](https://www.dropbox.com/sh/zri6u2vesqetuyy/AABR05VM8OfAX0lUXUu03xX4a?dl=0). Hasło jest takie same jak do tutoriali video tzn. apsikmopsik. W razie problemów z dostaniem się do plików - piszcie tutaj, lub załóżcie nowy issue.

Proszę aby każdy z Was wybrał sobie jeden plik oraz parę wydarzeń do porównania (np `face_90` vs `car_90`). Wpisujcie to co wybraliście poniżej w taki sposób:

```
Imię Nazwisko
nazwa pliku
warunek1 vs warunek2
```

Na przykład:

```
Julia Lang
CAT106 task2
car_180 vs face_180
```

W razie pytań - piszcie tutaj.

**Comment by WandaZ** [comment]
Wanda Zarzycka
CAT302 task2
face_0 vs face_90

**Comment by Juliajools** [comment]
Julia Adamus 
CAT207 task2 
face_0 vs face_180

**Comment by ZbyszekZ** [comment]
Zbigniew Zarzycki
CAT170 task2
face_0 vs face_90

**Comment by mmyszka** [comment]
Piotr Kruczkowski
CAT312 task2
face_0 vs face_90

**Comment by mmista** [comment]
Miłosz Miśta
CAT311 task2
face_0 vs face_90

2015-06-08 10:26 GMT+02:00 mmyszka notifications@github.com:

**Comment by szielinska** [comment]
Sabina Zielińska
CAT301 task2
face_0 vs face_90

**Comment by bpietka** [comment]
Bartłomiej Piętka
CAT309 task2
face_0 vs car_0

**Comment by marek123271** [comment]
Marek Sroczyński
CAT310 task2
face_0 vs face_180

**Comment by elorek** [comment]
Ewa Lorek
CAT114 task2
car_180 vs face_180

**Comment by mmagnuski** [comment]
Drogie dzielne studentki, drodzy dzielni studenci - proszę niech każdy z Was wybierze sobie elektrodę najulubieńszą na której zrobicie analizy. Dodaję o tym info w wiki o projekcie.

**Comment by bbednarz** [comment]
Bednarz Bartosz
CAT101 task2
face_0 vs face_90
Elektroda O1

**Comment by mmista** [comment]
Miłosz Miśta
CAT311 task2
face_0 vs face_90
Elektroda O1

2015-06-10 20:39 GMT+02:00 bbednarz notifications@github.com:

**Comment by jwisniewska** [comment]
Justyna WIśniewska
CAT206 task2
face_0 vs car_0
Elektroda O1

**Comment by jrafalski** [comment]
Jakub Rafalski
CAT102 task2
face_0 vs face_90
Elektroda O1

**Comment by kabel001** [comment]
Krystyna Bartos
CAT103 task2
face_0 vs face_90
O1

**Comment by mchylinski94** [comment]
Michał Chyliński
CAT203 task2
face_0 vs face_90
O1

**Comment by msliwinska** [comment]
Monika Śliwińska
CAT212 task2
face_0 vs.face_90
elektroda 01

2015-06-15 16:26 GMT+02:00 mchylinski94 notifications@github.com:

**Comment by szielinska** [comment]
Sabina Zielińska
CAT301 task 2
face_0 vs face_90
O1

**Comment by soniaszka** [comment]
Sonia Wontrucka
CAT305 task 2
face_0 vs face_90
elektroda 01

**Comment by jtopczewski** [comment]
Janek Topczewski
CAT303 task 2
face_0 vs face_90
elektroda O1

**Comment by EdSkamor** [comment]
Jakub Kojemski
CAT111 task 2
face_0 vs face_90
elektroda 01

**Comment by Bruno1208** [comment]
Bruno Słota
CAT304 task 2
face_0 vs face_00
elektroda 01

**Comment by anielas** [comment]
Aniela Ścisło 
CAT307 task 2 
face_0 vs face_90
elektroda 01

**Comment by jtopczewski** [comment]
Janek Topczewski
CAT303 task 2
face_0 vs face_90
elektroda E23

**Comment by mmagnuski** [comment]
Drodzy, chciałbym tylko poinformować, że nie ma elektrody `O1` w czepkach EGI, z których macie dane. Nie musicie deklarować elektrody tutaj. Ważne aby po prostu w projekcie zrobić oba porównania na jednej elektrodzie.

**Comment by kabel001** [comment]
Krystyna Bartos
Ja jednak zmieniam na CAT104 
face_0 face_90
*miałam bardzo duże problemy z poprzednim

**Comment by idakozarow** [comment]
Ida Kozarów
CAT 301
car0 vs face0

**Comment by Mwierzbieniec** [comment]
Maria Wierzbieniec
CAT306
face-0 face-180

**Comment by wiisienka48** [comment]
Katarzyna Wiśniewska
CAT109
car-0 car-90

**Comment by martyna0050** [comment]
Martyna Maciszewska
CAT211 task 2
face_0 face_180

**Comment by Searlas87** [comment]
Karol Adamczyk
CAT110
face_0 vs face_180

**Comment by Mwierzbieniec** [comment]
Grzegorz Lisek
CAT308
face_0 face_180
