### ISSUE TITLE
Odrabiane zajęcia

### ISSUE THREAD

**Issue by wiisienka48** [mmagnuski/AnalizaDanychEEG01#6]
Czy termin jest już oficjalnie ustalony i dzisiaj o 13.45 obędą się zajęcia? :)

**Comment by mmagnuski** [comment]
Tak zarządziło głosowanie (tylko jedna osoba zagłosowała od ostatniego wyniku i to dając terminowi 4b 5). Na wszelki wypadek rzucę Wam wszystkim maila. Chciałem to zrobić wczoraj, ale złośliwy wszechświat mi w tym przeszkodził. Do zobaczenia dziś!
