### ISSUE TITLE
Dziwne komponenty

### ISSUE THREAD

**Issue by bpietka** [mmagnuski/AnalizaDanychEEG01#7]
Po zrobieniu ICA trafiłem na takie dziwne komponenty które wyglądają jak dywan (tak aż nienaturalnie). Tak myślę że to artefakty ale wolę się upewnić. Mógłbyś Mikołaju poproszę spojrzeć na to, jeśli to nie problem? :>

![dziwne](https://cloud.githubusercontent.com/assets/11992773/8066508/4c9e0686-0ee8-11e5-9f3a-94bc383261cd.jpg)

**Comment by mmagnuski** [comment]
Tak jest - to są śliczne komponenty wyjaśniające artefakty związane z siecią elektryczną. Proszę zauważyć wielki czubek w częstotliwości 50 Hz. Stąd też ich "dywanistość" 50 Hz to wysoka częstotliwość - podobnie jak dywanu ogonki występują w krajobrazie dywanu z dużą częstotliwością. Dywan to jest w ogóle dobra nazwa na artefakty z sieci elektrycznej, myślę że zacznę stosować, dzięki!

**Comment by bpietka** [comment]
O czubka nie zauważyłem, rzeczywiście jest. Dziękuję i nie ma za co :)
