### ISSUE TITLE
Błąd przy próbie wyplotowania widma :/

### ISSUE THREAD

**Issue by bpietka** [mmagnuski/AnalizaDanychEEG01#8]
Mikołaju, wyskakuje mi taki błąd jeśli wpiszę że widmo ma się zaczynać przed bodźcem. Czy jest coś co mogę zrobić?
![blad](https://cloud.githubusercontent.com/assets/11992773/8130908/e18c9f3e-1116-11e5-9d76-570027071f6b.jpg)

**Comment by mmagnuski** [comment]
Może masz dane poepokowane tak, że nie nie masz tego czasu przed bodźcem, który chciałbyś mieć w widmie. Jakie masz epokowanie?
(upewnij się też, że masz najnowszego eeglaba)

**Comment by bpietka** [comment]
Wcześniej rzeczywiście wpisywałem czas tak jakby sprzed epoki. Aktualnie wpisałem taki który mieści się w epoce ale teraz z kolei wyrzuciło mi takie rzeczy. 
![image](https://cloud.githubusercontent.com/assets/11992773/8145771/3c505686-1216-11e5-85fe-26d1329dffde.png)
Matlab w tle drukuje w kółko:
Value of timesout must be <= frames-winsize, timeout adjusted to 0

a potem wyskakuje błąd związany z wymiarami macierzy i puste miejsce na wykres.

Wersje eeglaba mam najświeższą.

**Comment by mmagnuski** [comment]
Nie jestem pewien co ma przechowywać `timesout` i w związku z tym na ile problem wynika właśnie z ustawienia tej zmiennej na zero (ani w funkcji `topoplot` ani w `spectopo` nie ma tej zmiennej), ale brzmi to podejrzanie. Możesz spróbować:
- upewnić się, że czas wpisujesz w odpowiednich jednostkach (w milisekundach, nie sekundach)
- spróbuj, zgodnie ze skryptowym tutorialem widmowym zrobić widmo komendą (tzn. bez klikania w interfejs eeglaba) - trzeba dodać do argumentów komendy `pop_spectopo` - `'plot'`, `'off'` :  

```
[widmo, freq] = pop_spectopo(EEG, 1, [0  500], 'EEG' , 'percent', 100, 'plot', 'off');
```
- spróbuj wyplotować widmo bez zmieniania domyślnych parametrów (domyślnie jest z całej epoki) - czy wtedy błąd również się pojawia?

Poza tym: możesz albo złapać mnie na swps w tym tygodniu (tzn. od poniedziałku) albo opisać dokładniej w jakim kontekście pojawia się problem tzn:
- jakie dane
- jakie filtrowanie i epokowanie
- co dokładnie klikasz i wpisujesz  

Wtedy będę mógł zreprodukować Twój problem i zdebugować sprawę.

**Comment by bpietka** [comment]
To ja jeszcze dzisiaj popróbuje, ale mógłbym jakoś jutro właśnie wpaść spróbować zdiagnozować. O której i gdzie mógłbym przyjść?

**Comment by bpietka** [comment]
Wymiary epoki to -0.25 do 1, dane 'CAT309 task2' do projektu poepokowane względem bodźców face_0 oraz car_0 oraz 'FIR filter' dolna krawędź 'frequency pass band' ustawiona na 1Hz, górna na 0. Oraz po odrzuceniu komponentów po ICA.

I tak, jeśli wyplotuje widmo na domyślnych parametrach(-252 996) (przez interfejs graficzny) to jest okej, plotuje się. Jeżeli zmieniam parametry inne niż zakres czasowy (i wpisuje/wpisywałem w ms), to też plotuje. Jak próbuje wpisać żeby wyplotował od początku epoki do prezentacji bodźca (wpisuje: -252 0) to wtedy jest ten błąd z wymiarami macierzy i ten 'timesout' cały. 

Jeżeli plotuje 'ręcznie' to zwróciło mi to:
"

> > [widmo, freq] = pop_spectopo(EEG, 1, [0  996], 'EEG' , 'percent', 100, 'plot', 'off');
> > pop_spectopo(): selecting time range   0.00 ms to 996.00 ms (points 64 to 313)
> > Computing spectraLicense checkout failed.
> > License Manager Error -5
> > Cannot find a license for Signal_Toolbox.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2014b/5

Diagnostic Information:
Feature: Signal_Toolbox 
License path: C:\Users\oem\AppData\Roaming\MathWorks\MATLAB\R2014b_licenses\license_oem-Komputer_1075922_R2014b.lic;C:\Program Files\MATLAB\R2014b\licenses\license.dat;C:\Program Files\MATLAB\R2014b\licenses 
Licensing error: -5,357.

Signal processing toolbox (SPT) absent: spectrum computed using the pwelch()
function from Octave which is suposedly 100% compatible with the Matlab pwelch function
 (window length 250; fft length: 512; overlap 0):
................................................................
"
I dalej nic się nie dzieje.

Najchętniej to bym właśnie przyszedł na konsultacje, jeśli to nie problem.

**Comment by mmagnuski** [comment]
A, nie masz signal processing toolbox - stąd może być problem. Jeszcze
spraqdzimy. Jutro ok 13 będę w szkole, krążył będę, pisz, łap!
14 cze 2015 22:22 "bpietka" notifications@github.com napisał(a):

> Wymiary epoki to -0.25 do 1, dane 'CAT309 task2' do projektu poepokowane
> względem bodźców face_0 oraz car_0 oraz 'FIR filter' dolna krawędź
> 'frequency pass band' ustawiona na 1Hz, górna na 0.
> 
> I tak, jeśli wyplotuje widmo na domyślnych parametrach(-252 996) (przez
> interfejs graficzny) to jest okej, plotuje się. Jeżeli zmieniam parametry
> inne niż zakres czasowy (i wpisuje/wpisywałem w ms), to też plotuje. Jak
> próbuje wpisać żeby wyplotował od początku epoki do prezentacji bodźca
> (wpisuje: -252 0) to wtedy jest ten błąd z wymiarami macierzy i ten
> 'timesout' cały.
> 
> Jeżeli plotuje 'ręcznie' to zwróciło mi to:
> "
> 
>  [widmo, freq] = pop_spectopo(EEG, 1, [0 996], 'EEG' , 'percent', 100,
> 'plot', 'off');
> pop_spectopo(): selecting time range 0.00 ms to 996.00 ms (points 64 to
> 313)
> Computing spectraLicense checkout failed.
> License Manager Error -5
> Cannot find a license for Signal_Toolbox.
> 
>  Troubleshoot this issue by visiting:
> http://www.mathworks.com/support/lme/R2014b/5
> 
> Diagnostic Information:
> Feature: Signal_Toolbox
> License path:
> C:\Users\oem\AppData\Roaming\MathWorks\MATLAB\R2014b_licenses\license_oem-Komputer_1075922_R2014b.lic;C:\Program
> Files\MATLAB\R2014b\licenses\license.dat;C:\Program
> Files\MATLAB\R2014b\licenses
> Licensing error: -5,357.
> 
> Signal processing toolbox (SPT) absent: spectrum computed using the
> pwelch()
> function from Octave which is suposedly 100% compatible with the Matlab
> pwelch function
> (window length 250; fft length: 512; overlap 0):
> ................................................................
> "
> I dalej nic się nie dzieje.
> 
> Najchętniej to bym właśnie przyszedł na konsultacje, jeśli to nie problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mmagnuski/AnalizaDanychEEG01/issues/8#issuecomment-111873415
> .

## 

---

**Comment by bpietka** [comment]
Ściągnąłem trialową wersję, tego signal processing toolbox , ale dalej nie działa :/

**Comment by mmagnuski** [comment]
A jak było w sali komputerowej?
Jeżeli wciąż był problem to opisz jak masz poepokowane dane i jak prosisz o widmo.

**Comment by bpietka** [comment]
Okazało się że moje epokowanie przeszkadzało. Teraz zrobiłem po równo przed i po bodźcu i jest okej (na laptopie też). 

Wtedy w sali nie wiedzieliśmy dokładnie jak zrobić to widmo przed i po dla 1 elektrody, ale po notatkach jakoś doszliśmy do takiego rozwiązania:

 najpierw wykonaliśmy to:
figure; [widmo, freq]= pop_spectopo(EEG, 1, [-500 0], 'EEG' , 'freq', [6 10 22], 'freqrange',[1 65]);

 potem to:
figure; [widmo2, freq]= pop_spectopo(EEG, 1, [0 500], 'EEG' , 'freq', [6 10 22], 'freqrange',[1 65]);

a potem to:

figure;
hold on;
plot (freq, widmo (30, :),'g');
plot (freq, widmo2 (30, :),'r');
legend ('przed bodzcem', 'po bodzcu');

**Comment by mmagnuski** [comment]
`figure` w `pop_spectopo` nie jest potrzebne skoro plotujemy sami:

``` matlab
widmo_pre = pop_spectopo(EEG, 1, [-500 0], 'EEG', 'plot', 'off');
[widmo_post, freq] = pop_spectopo(EEG, 1, [0 500], 'EEG', 'plot', 'off');
```

Plotowanie dokładnie tak jak napisałeś:

``` matlab
elec = 30; % tutaj numer elektrody
figure; hold on;
plot (freq, widmo_pre(elec, :), 'g');
plot (freq, widmo_post(elec, :),'r');
legend ('przed bodzcem', 'po bodzcu');
```

**Comment by mmagnuski** [comment]
Jeżeli chcecie zrobić wykres widma tylko dla jakiegoś zakresu częstotliwości, przyda się:

``` matlab
% tutaj ustawiamy zakres częstotliwości:
rng = [0, 75];

% szukamy próbek widma najbliższych zakresowi, jakiego chcemy:
cnt = @(x) x(1) : x(2);
freq_rng = cnt( arrayfun(@(x) find(min(abs(freq - x)) == abs(freq - x)), rng) );

% plotujemy widmo tak:
plot(freq(freq_rng), widmo(elec, freq_rng), 'g');
```

**Comment by bpietka** [comment]
Dziękuje :]
