### ISSUE TITLE
Psotne elektrody

### ISSUE THREAD

**Issue by Mwierzbieniec** [mmagnuski/AnalizaDanychEEG01#9]
Wybrany przeze mnie sygnał bogaty jest w psotne elektrody, kiedy jednak chcę je wykluczyć z elitarnego grona tych, które dostąpią zaszczytu bycia poddanymi ICA, wyskakuje mi następujący komunikat:
![image](https://cloud.githubusercontent.com/assets/12977369/8268079/c315f91c-1777-11e5-9f96-0004c882f3b5.png)
a po kliknięciu "interrupt":
![image](https://cloud.githubusercontent.com/assets/12977369/8268084/f8c02e2a-1777-11e5-824e-8338b438619a.png)

Macie może pomysł jak się z tym rozprawić?

**Comment by bbednarz** [comment]
Ten pierwszy komunikat masz robić NIC :)
Masz poczekać aż zniknie i wtedy wszystko działa jak należy, bo wtedy ICA
robi swoje i musisz poczekać aż się skończy, no chyba że chcesz przerwać
proces ICA to wtedy naciskasz INTERUPT :)
I jak się samo dobrze zrobi to wtedy to kolejne nie powinno się pojawić :)

W dniu 20 czerwca 2015 18:13 użytkownik Mwierzbieniec <
notifications@github.com> napisał:

**Comment by mmagnuski** [comment]
:+1:
